meta_product_name: "Gabriel Campista Photography"
meta_title: "Gabriel Campista Photography"
meta_description: "I'd like to invite you to my Photography Portfolio."
meta_image: "logotag.jpeg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards