meta_product_name: "Gabriel Campista Photography"
meta_title: "Gabriel Campista Photography"
meta_description: "This is some of my cool photos: I'd like to invite you to my Photography Portfolio."
meta_image: "foto55.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards